linux/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from rest_framework import routers, serializers, viewsets
from django.conf.urls import url
# from myapp.views import ScrummyUserViewSet, ScrummyGoalsViewSet, GoalStatusViewSet
from myapp import views
from django.conf import settings
router = routers.DefaultRouter()
# router.register(r'user', ScrummyUserViewSet)
# router.register(r'goals', ScrummyGoalsViewSet)
# router.register(r'status', GoalStatusViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/user/', views.signup_profile, name='user_signup'),
    path('accounts/signup/admin/', views.signup, name='admin_signup'),
    re_path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url('api/', include(router.urls)),

    # path('api/scrummyusers/', views.scrummy_list, name="scrummy_list"),
    # path('api/scrummyusers/<int:pk>/', views.scrummy_detail, name="scrummy_detail"),

]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    # urlpatterns += static(settings.MEDIA_URL,
    #                       document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL,
    #                       document_root=settings.STATIC_ROOT)

myapp/urls.py
from django.urls import path

from . import views
app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('task/',views.add_task, name='add_task'),
    path('user/task/', views.user_add_task, name="user_add_task"),
    path('add/status/', views.add_status, name="add_status"),
    # path('filter/<int:task_id>/', views.filter, name='filter'),
    path('move/<int:ta_id>/',views.move_goal, name='move_goal'),
    path('delete/<int:pk>/',views.user_delete, name='user_delete'),
    # path('adduser/', views.add_user, name='add_user'),
    # path('goals/', views.GoalView.as_view(), name='goal'),
    # path('home/', views.home, name='home'),
    #path('scrummy/', views.ScrummyUserViewSet.as_view('list'), name='scrummy'),
    path('api/users/', views.UserCreateView.as_view(), name="create_users"),
    # path('api/tasks/users', views.UserTaskCreateView.as_view(), name="create_users_tasks"),
    path('api/users/<int:pk>/', views.UserDetailsView.as_view(), name="detail_users"),
    path('api/admin/', views.AdminCreateView.as_view(), name="create_admin"),
    path('api/admin/<int:pk>/', views.AdminDetailsView.as_view(), name="detail_admin"),
    path('api/tasks/', views.ScrummyGoalsCreateView.as_view(), name="create_tasks"),
    path('api/tasks/<int:pk>', views.ScrummyGoalsDetailsView.as_view(), name="detail_tasks"),
    path('api/status/', views.StatusCreateView.as_view(), name="create_status"),
    # path('api/login/', views.apilogin)

]

myapp/forms.py
from django.forms import ModelForm
from django import forms
from .models import ScrummyUser, ScrummyGoals, GoalStatus, Organization, Users, Admin
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.forms import UserCreationForm
# from myapp.models import User, ScrummyUser, Admin, Organization
from django.db import transaction
from .choice import role
from django.contrib.auth.models import User


class OrganizationForm(forms.ModelForm):

    # organization = forms.CharField(max_length=255)

    class Meta:
        model = Organization
        fields = ['organization']



class AdminSignUpForm(UserCreationForm):
    organization = forms.CharField(required=True, max_length=255, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta(UserCreationForm.Meta):
        model = Users
        fields = ['username','email','organization']

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_admin = True
        user.save()
        organization = self.cleaned_data.get('organization')
        admin = Admin()
        admin.organization = organization
        admin.save()
        # if commit:
        #     user.save()
        return user



class UserForm(UserCreationForm):
    role = forms.ChoiceField(choices=role)
    org = forms.ModelChoiceField(
        queryset=Admin.objects.all(),
    )
    class Meta:
        model = Users
        fields = ('first_name', 'last_name', 'email','username','role', 'org')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_user = True
        user.save()
        role = self.cleaned_data.get('role')
        org = self.cleaned_data.get('org')
        profile = ScrummyUser()
        profile.user = user
        profile.role =role
        profile.org = org
        profile.save()

        return user


class ScrummyForm(forms.ModelForm):
    class Meta:
        model = ScrummyUser
        fields = ( 'role', 'org')

class ChangeTaskForm(forms.ModelForm):
    class Meta:
        model = ScrummyGoals
        fields = ['target_name']
#
#
#
# class AddUserForm(forms.ModelForm):
#
#     password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
#     password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
#     class Meta:
#
#         model = ScrummyUser
#         widgets = {'password1' : forms.PasswordInput(render_value=True), 'password2' : forms.PasswordInput(render_value=True)}
#
#         fields = ['first_name','last_name','username','password1','password2']
#
#     def clean_password2(self):
#         password1 = self.cleaned_data.get("password1")
#         password2 = self.cleaned_data.get('password2')
#
#         if password1 and password2 and password1 != password2:
#             raise forms.ValidationError("Password Dont match")
#         return password2
#
#     def save(self, commit=True):
#         user = super(AddUserForm, self).save(commit=False)
#         user.set_password(self.cleaned_data["password1"])
#         user.is_active = False
#         if commit:
#             user.save()
#         return user

class AddTaskForm(forms.ModelForm):


    class Meta:
        model = ScrummyGoals
        fields = ['task','target_name','user_name']


class AddStatusForm(forms.ModelForm):
    class Meta:
        model = GoalStatus
        fields = ['target']

myapp/views.py
from django.shortcuts import render, render_to_response, redirect
from django.http import Http404
# from .forms import AddTaskForm, AddUserForm, ChangeTaskForm
from django.views.decorators.csrf import csrf_exempt
#from django.views.decorators.csrf import csrf_protect
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import ScrummyUser, ScrummyGoals, GoalStatus, Users, Admin

from django.template.response import TemplateResponse
from django.contrib.auth.decorators import permission_required
# from django.contrib.auth.models import User
from django import template
from django.views import generic
from rest_framework import routers, serializers, viewsets
from rest_framework.parsers import JSONParser
from .serializer import  ScrummyGoalsSerializer, ScrummySerializer, UsersSerializers, AdminSerializer, StatusSerializer
from django.shortcuts import redirect
from myapp.forms import AdminSignUpForm, OrganizationForm, UserForm, ScrummyForm, AddTaskForm, AddStatusForm, ChangeTaskForm
from django.views.generic import CreateView
from django.contrib.auth import login, authenticate
from django.db import transaction
from django.contrib import messages
from django.shortcuts import get_object_or_404
from rest_framework import generics
from rest_framework.decorators import api_view, permission_classes
from rest_framework.authtoken.models import Token
from rest_framework.permissions import AllowAny
from rest_framework.status import (
    HTTP_400_BAD_REQUEST,
    HTTP_404_NOT_FOUND,
    HTTP_200_OK
)
from rest_framework.response import Response

def index(request):
    if request.user.is_authenticated:
        return redirect('myapp:home')
    return render(request, 'myapp/index.html')

def home(request):

    try:
        # users = User.objects.all().select_related('scrummyuser')
        users = Users.objects.all().select_related('scrummyuser')
        num_user = ScrummyUser.objects.all()
        task = GoalStatus.objects.all()
        con = {'user':num_user, 'task':task, 'users':users}
        return render(request, 'myapp/home.html', con)
    except ScrummyUser.DoesNotExist as e:
        raise Http404("Object does not exist")

def signup(request):
    if request.method == 'POST':
        adminForm = AdminSignUpForm(request.POST)
        # orgForm = OrganizationForm(request.POST)
        if adminForm.is_valid():
            adminForm.save()
            # orgForm.save()
            username = adminForm.cleaned_data.get('username')
            raw_password = adminForm.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, ('Your profile was successfully created!'))
            return redirect('myapp:home')
        else:
            messages.error(request, ('Please correct the error below.'))
    else:

        adminForm = AdminSignUpForm()
        # orgForm = OrganizationForm()

    return render(request, 'registration/signup_form.html', {'form': adminForm})


def signup_profile(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():

            user = form.save()
            # user.is_active = False
            user.save()

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('myapp:home')
    else:
        form = UserForm()

    return render(request, 'registration/user_signup.html', {
            'form': form,

        })

# @transaction.atomic
# def signup_profile(request):
#     if request.method == 'POST':
#         user_form = UserForm(request.POST)
#         profile_form = ScrummyForm(request.POST)
#         if user_form.is_valid() and profile_form.is_valid():
#             user_form.save()
#             profile_form.save()
#             username = user_form.cleaned_data.get('username')
#             raw_password = user_form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             messages.success(request, ('Your profile was successfully created!'))
#             return redirect('myapp:home')
#         else:
#             messages.error(request, ('Please correct the error below.'))
#     else:
#         user_form = UserForm()
#         profile_form = ScrummyForm()
#     return render(request, 'registration/user_signup.html', {
#         'user_form': user_form,
#         'profile_form': profile_form
#     })



def filter(request, task_id):
    var = GoalStatus.objects.filter(pk=task_id)
    out = " ".join([q.day_target for q in var])
    return HttpResponse("The Goal status for day target id %s is %s " % (task_id, out))

def move_goal(request, ta_id):
    mssg = ""

    if request.user.is_authenticated:
        # curr_user = request.user
        curr_user_group = request.user.scrummyuser.role
        admin = request.user.is_admin

        try:
            task = ScrummyGoals.objects.get(id=ta_id)
            task_status = task.target_name
        except ScrummyGoals.DoesNotExist:
            raise Http404("There is no task with id ")

        if curr_user_group:

            if request.method == "POST":
                form = ChangeTaskForm(request.POST or None, instance=task)

                if form.is_valid():
                    my_status = request.POST.get('target_name')
                    status_obj = GoalStatus.objects.get(id=my_status)

                        #Owner Permission
                    if admin:
                        task_status = status_obj
                        pass
                        # admin permission
                    elif str(curr_user_group) == 'AD':
                        if str(task_status) == 'Day' and status_obj.target == 'Verify':
                            task_status = status_obj
                        else:
                            messages.error(request, ('You do not have permission to move this task, '
                                                     'You can only move from Daily task to Verify'))
                            return redirect('myapp:home')
                            # return HttpResponse("You do not have permission to move this task, "
                            #                     "You can only move from Daily task to Verify")

                            # Quality analyst permission
                    elif str(curr_user_group) == 'QA':
                        if str(task_status) == 'Verify' and status_obj.target == 'Done':
                            task_status = status_obj
                        else:
                            messages.error(request, ('You do not have permission to move this task,'
                                                     ' You can only move from verify to Done'))
                            return redirect('myapp:home')
                            # return HttpResponse("You do not have permission to move this task,"
                            #                     " You can only move from verify to Done")

                            # Developer permission
                    elif str(curr_user_group) == 'DEV':
                        if str(task_status) == "Week" and status_obj.target == "Day" or str(task_status) == "Day" and status_obj.target =="Week":
                            task_status = status_obj
                        else:
                            messages.error(request, ('You do not have permission to move this task!'))
                            return redirect('myapp:home')
                            # return HttpResponse("You do not have permission to move this task,"
                            #                     " You can only move from Weekly target to Daily target")

                    else:
                        messages.error(request, ('You do not have permission to change the goal status!'))
                        return redirect('myapp:home')
                        # mssg += 'You do not have permission to change the goal status'
                        # return HttpResponse('No permission defined for your group')
                    task.save()

                    messages.success(request, ('Your status was successfully created!'))
                    return redirect('myapp:home')

            else:
                form = ChangeTaskForm()

            args = {'form': form}

            return render(request, 'myapp/move_task.html', args)
        else:
            return HttpResponse("User does not belong to any group")
    else:
        return HttpResponse("Access denied")


def add_task(request):
    users = ScrummyUser.objects.all()
    status = GoalStatus.objects.all()
    # target = ScrummyGoals.objects.get(target_name_id=week_status.id)


    if request.method == 'POST':
        if request.POST.get('task') and request.POST.get('goal') and request.POST.get('user'):
            task = ScrummyGoals()
            task.target_name_id = int(request.POST.get('goal'))
            task.user_name_id = request.POST.get('user')
            task.task = request.POST.get('task')
            task.save()
            messages.success(request, ('Your task for this employee was successfully created!'))
            return redirect('myapp:home')

    con = {

        'status':status,
        'users':users
    }
    return render(request, 'myapp/add_task.html', con)


def add_status(request):
    if request.POST:
        form = AddStatusForm(request.POST)
        if form.is_valid():
            form.save()

myapp/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Django School{% endblock %}</title>
     {% comment %} <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}"> {% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    {% comment %} {% if user.is_authenticated and user.is_teacher %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/teachers.css' %}">
    {% else %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/students.css' %}">
    {% endif %}  {% endcomment %}
  </head>
  <body>
    <a href="https://github.com/sibtc/django-multiple-user-types-example"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"></a>
    <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h2 class="logo">
                <a href="{% url 'myapp:index' %}">
                  An app to manage technical Users
                  {% if request.user.is_authenticated %}
                    {% if request.user.is_admin %}
                      <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Admin View"></span>
                      <p>Admin</p>
                    {% else %}
                      <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Student profile"></span>
                      <p>User</p>
                    {% endif %}
                  {% endif %}
                </a>
              </h2>
            </div>
            <div class="col-6 text-right">
              {% if request.user.is_authenticated %}
                <p class="pt-3">Logged in as <strong>{{ request.user.username }}</strong>. <a href="{% url 'logout' %}">Log out</a>.</p>
              {% else %}
                <a href="{% url 'login' %}" class="btn btn-light" role="button">Log in</a>
                {% comment %} <a href="{% url 'signup' %}" class="btn btn-primary" role="button">Sign up</a> {% endcomment %}
              {% endif %}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
          <footer>
          
            <a href="https://github.com/Akoh1/task-manager">GitHub repository</a>
          </footer>
        </div>
      </div>
    </div>
    {% comment %} <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>{% endcomment %}
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
  </body>
</html>